### ISSUE TITLE
Update info on pyaudio and scikits.audiolab dependencies for I/O

### ISSUE THREAD

**Issue by mmoussallam** [mmoussallam/PyMP#10]
We need to let user know that PyMP I/O may benefit from pyaudio and scikits.audiolab facilities (since the wave module itself cannot handle other types than wav)

**Comment by agramfort** [comment]
you want to get back to this  :)

>

**Comment by mmoussallam** [comment]
deep down probably yes :) 

Congrats on all your recent prizes by the way !

**Comment by agramfort** [comment]
Thx :)
